# Site settings
title: 稚子夏日
email: childsummer (at) outlook.com
description: > # this means to ignore newlines until "baseurl:"
  人们并不知道要追求什么，<br>他们只知道正在追求什么。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://childsummer.github.io" # the base hostname & protocol for your site
twitter_username: #zixia
github_username:  childsummer

# Build settings
markdown: kramdown
